apiVersion: v2
name: moodle
description: Production-oriented Moodle Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "4.5"
keywords:
  - moodle
  - lms
  - education
home: https://moodle.org
sources:
  - https://github.com/moodle/moodle
maintainers:
  - name: platform-team
